export const questions = [
  {
    id: 1,
    name: "What’s your name?",
    category: "Personal",
    spanish: "¿Cómo te llamas?",
  },
  {
    id: 2,
    name: "What’s your last name / surname?",
    category: "Personal",
    spanish: "¿Cuál es tu apellido?",
  },
  {
    id: 3,
    name: "What do you do for a living?",
    category: "Personal",
    spanish: "¿A qué te dedicas?",
  },
  {
    id: 4,
    name: "Where are you from?",
    category: "Personal",
    spanish: "¿De dónde eres?",
  },
  {
    id: 5,
    name: "Where do you work?",
    category: "Trabajo",
    spanish: "¿Dónde trabajas?",
  },
  {
    id: 6,
    name: "How old are you?",
    category: "Personal",
    spanish: "¿Cuántos años tienes?",
  },
  {
    id: 7,
    name: "Are you married?",
    category: "Relaciones",
    spanish: "¿Estás casado?",
  },
  {
    id: 8,
    name: "Do you have a boyfriend / girlfriend?",
    category: "Relaciones",
    spanish: "¿Tienes novio / novia?",
  },
  {
    id: 9,
    name: "Do you have any brothers or sisters?",
    category: "Familia",
    spanish: "¿Tienes hermanos?",
  },
  {
    id: 10,
    name: "What are you doing?",
    category: "Acciones",
    spanish: "¿Qué estás haciendo?",
  },
  {
    id: 11,
    name: "Where do you live?",
    category: "Personal",
    spanish: "¿Dónde vives?",
  },
  {
    id: 12,
    name: "How are you?",
    category: "Saludo",
    spanish: "¿Cómo estás?",
  },
  {
    id: 13,
    name: "How do you feel?",
    category: "Emociones",
    spanish: "¿Cómo te sientes?",
  },
  {
    id: 14,
    name: "What’s your favorite food?",
    category: "Gustos",
    spanish: "¿Cuál es tu comida favorita?",
  },
  {
    id: 15,
    name: "Have you got a car?",
    category: "Propiedades",
    spanish: "¿Tienes un coche?",
  },
  {
    id: 16,
    name: "Are you ready?",
    category: "Acciones",
    spanish: "¿Estás listo?",
  },
  {
    id: 17,
    name: "How was it?",
    category: "Opiniones",
    spanish: "¿Cómo estuvo?",
  },
  {
    id: 18,
    name: "How did it go?",
    category: "Opiniones",
    spanish: "¿Cómo fue?",
  },
  {
    id: 19,
    name: "How did it happen?",
    category: "Sucesos",
    spanish: "¿Cómo ocurrió?",
  },
  {
    id: 20,
    name: "How’s it going? (informal)",
    category: "Saludo",
    spanish: "¿Cómo te va?",
  },
  {
    id: 21,
    name: "Where are you going?",
    category: "Acciones",
    spanish: "¿Dónde vas?",
  },
  {
    id: 22,
    name: "Where is my…?",
    category: "Ubicación",
    spanish: "¿Dónde está mi…?",
  },
  {
    id: 23,
    name: "What’s the weather like?",
    category: "Clima",
    spanish: "¿Qué tiempo hace?",
  },
  {
    id: 24,
    name: "What time is it?",
    category: "Tiempo",
    spanish: "¿Qué hora es?",
  },
  {
    id: 25,
    name: "Who said that?",
    category: "Sucesos",
    spanish: "¿Quién dijo eso?",
  },
  { id: 26, name: "When?", category: "Tiempo", spanish: "¿Cuándo?" },
  {
    id: 27,
    name: "What’s that?",
    category: "Curiosidad",
    spanish: "¿Qué es eso?",
  },
  {
    id: 28,
    name: "What do you like?",
    category: "Gustos",
    spanish: "¿Qué te gusta?",
  },
  {
    id: 29,
    name: "What do you think about…?",
    category: "Opiniones",
    spanish: "¿Qué piensas acerca de…?",
  },
  {
    id: 30,
    name: "What would you like to eat?",
    category: "Comida",
    spanish: "¿Qué te gustaría comer?",
  },
  {
    id: 31,
    name: "What would you like to drink?",
    category: "Bebida",
    spanish: "¿Qué te gustaría beber?",
  },
  {
    id: 32,
    name: "Where did you go?",
    category: "Acciones",
    spanish: "¿Dónde fuiste?",
  },
  {
    id: 33,
    name: "Where were you?",
    category: "Acciones",
    spanish: "¿Dónde estabas?",
  },
  {
    id: 34,
    name: "What’s new?",
    category: "Actualidad",
    spanish: "¿Qué hay de nuevo?",
  },
  {
    id: 35,
    name: "What’s up? / What’s happening?",
    category: "Sucesos",
    spanish: "¿Qué pasa?",
  },
  {
    id: 36,
    name: "Who is your favourite singer?",
    category: "Gustos",
    spanish: "¿Cuál es tu cantante favorito?",
  },
  {
    id: 37,
    name: "Where were you born?",
    category: "Personal",
    spanish: "¿Dónde naciste?",
  },
  {
    id: 38,
    name: "Do you like living in your country?",
    category: "Opiniones",
    spanish: "¿Te gusta vivir en tu país?",
  },
  {
    id: 39,
    name: "Where is the doctor?",
    category: "Ubicación",
    spanish: "¿Dónde está el doctor?",
  },
  {
    id: 40,
    name: "What’s your address?",
    category: "Personal",
    spanish: "¿Cuál es tu dirección?",
  },
  {
    id: 41,
    name: "What’s your (tele)phone number?",
    category: "Personal",
    spanish: "¿Cuál es tu teléfono?",
  },
  {
    id: 42,
    name: "Have you got any children?",
    category: "Familia",
    spanish: "¿Tienes hijos?",
  },
  {
    id: 43,
    name: "Can you play tennis?",
    category: "Habilidades",
    spanish: "¿Puedes jugar al tenis?",
  },
  {
    id: 44,
    name: "Can you speak Spanish?",
    category: "Habilidades",
    spanish: "¿Hablas castellano?",
  },
  {
    id: 45,
    name: "Could you do it?",
    category: "Habilidades",
    spanish: "¿Podrías hacerlo?",
  },
  {
    id: 46,
    name: "How can I help you?",
    category: "Ofrecimiento",
    spanish: "¿Puedo ayudarte?",
  },
  {
    id: 47,
    name: "Can I try it on?",
    category: "Acciones",
    spanish: "¿Puedo probármelo?",
  },
  {
    id: 48,
    name: "What’s that?",
    category: "Curiosidad",
    spanish: "¿Qué es eso?",
  },
  {
    id: 49,
    name: "Can I open the window?",
    category: "Acciones",
    spanish: "¿Puedo abrir la ventana?",
  },
  {
    id: 50,
    name: "What would you like to do?",
    category: "Acciones",
    spanish: "¿Qué te gustaría hacer?",
  },
  {
    id: 51,
    name: "How much does it cost?",
    category: "Compras",
    spanish: "¿Cuánto cuesta?",
  },
  {
    id: 52,
    name: "How would you like to pay?",
    category: "Compras",
    spanish: "¿Cómo te gustaría pagar?",
  },
  {
    id: 53,
    name: "Where is the nearest supermarket?",
    category: "Ubicación",
    spanish: "¿Dónde está el supermercado más cercano?",
  },
  {
    id: 54,
    name: "Is this your book?",
    category: "Propiedades",
    spanish: "¿Es este tu libro?",
  },
  {
    id: 55,
    name: "What does he / she look like?",
    category: "Descripción",
    spanish: "¿Cómo es él/ella?",
  },
  {
    id: 56,
    name: "What would you like to eat?",
    category: "Comida",
    spanish: "¿Qué te gustaría comer?",
  },
  {
    id: 57,
    name: "What’s it about?",
    category: "Curiosidad",
    spanish: "¿De qué trata?",
  },
  {
    id: 58,
    name: "What do you think about that film?",
    category: "Opiniones",
    spanish: "¿Qué piensas de esa película?",
  },
  {
    id: 59,
    name: "How difficult or easy is it?",
    category: "Dificultad",
    spanish: "¿Qué tan difícil o fácil es?",
  },
  {
    id: 60,
    name: "What are you going to do tomorrow?",
    category: "Acciones",
    spanish: "¿Qué vas a hacer mañana?",
  },
  {
    id: 61,
    name: "Would you like to meet me for a drink?",
    category: "Invitación",
    spanish: "¿Quieres quedar conmigo para tomar algo?",
  },
  {
    id: 62,
    name: "Would you like to go out with me?",
    category: "Invitación",
    spanish: "¿Te gustaría salir conmigo?",
  },
  {
    id: 63,
    name: "What shall we do about this?",
    category: "Acciones",
    spanish: "¿Qué debemos hacer sobre esto?",
  },
  {
    id: 64,
    name: "Why don’t we go out for a run?",
    category: "Invitación",
    spanish: "¿Por qué no salimos a correr?",
  },
  {
    id: 65,
    name: "What shall we have for dinner?",
    category: "Comida",
    spanish: "¿Qué cenamos?",
  },
  {
    id: 66,
    name: "Would you like to come to my place?",
    category: "Invitación",
    spanish: "¿Quieres venir a mi casa?",
  },
];
